FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
# 도커 사용시에는 외부 접속이 필요하므로, 127.0.0.1 대신 0.0.0.0으로 모든 접근을 허용하게 두는게 맞다!