services:
  postgres:
    image: postgres:17
    container_name: CEL_todo_container
    restart: always
    environment:
      POSTGRES_USER: cakesniffer
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CEL_todos_db
    ports:
      - "5433:5432"  # 로컬에서는 5433 포트를 사용 포트 충돌을 방지하기 위해서 변경 실제로 5432포트 사용시 충돌해서 db툴로 접근할 수 없었음음
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
    container_name: fastapi_container
    #노트북 성능 이슈로 sleep 3초 부여
    command: >
      sh -c "sleep 3 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
